services:
    mysql:
        image: mysql:5
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_PORT: ${DB_PORT}
        ports:
            - '${DB_PORT}:3306'
        container_name: circuittrade_mysql
        volumes:
            - ./mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: ${DB_PORT}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        container_name: circuittrade_phpmyadmin
        ports:
            - '8080:80'
